export const IPC_CHANNELS = {
  categoryList: 'category:list',
  categoryCreate: 'category:create',
  categoryUpdate: 'category:update',
  categoryDelete: 'category:delete',
  categoryReorder: 'category:reorder',
  cardList: 'card:list',
  cardCreate: 'card:create',
  cardUpdate: 'card:update',
  cardDelete: 'card:delete',
  cardReorder: 'card:reorder',
  cardSearch: 'card:search',
  cardOpen: 'card:open',
  cardImport: 'card:import',
  securityGetSettings: 'security:getSettings',
  securityHasPassword: 'security:hasPassword',
  securityUpdateSettings: 'security:updateSettings',
  securityUnlock: 'security:unlock',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  systemListBrowsers: 'system:listBrowsers',
  systemGetVersion: 'system:getVersion',
} as const;
